/*
 * Swagger MapSNS
 *
 * gobackend api
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package request

type Model struct {
	ID int

	Body      string `json:"body,omitempty" binding:"required"`
	ParentID int
}

// Parent - A single parent.
type ModelQuery struct {
	Query    string `form:"query"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}
