version: '3.7'
services:
  go:
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    restart: always
    ports:
      - ${GO_PORT}:8080
    depends_on:
      - mariadb
    env_file:
      - .env.docker

    # volumes:
    #   - ../:/go/src/
  mariadb:
    build: ./docker/mariadb
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../docker_data/go-backend/db/data:/var/lib/mysql
    env_file:
      - .env.docker
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mariadb
    volumes:
     - ../docker_data/go-backend/phpmyadmin/sessions:/sessions
    env_file:
      - .env.docker
# volumes:
#   wordpress:
#   mariadb:
