/*
 * Swagger MapSNS
 *
 * gobackend api
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package domain

import (
	"gorm.io/gorm"

	"gobackend/request"
)

type Model struct {
  Base
	Body string `json:"body,omitempty"`
	ParentID int `json:"parent_id,omitempty"`

	DeletedAt gorm.DeletedAt
}


func (model *Model) SetRequest(request request.Model, parentID int) {
	model.Body = request.Body
	model.ParentID = parentID
	return
}

func (model *Model) SetUpdateRequest(request request.Model) {
	model.Body = request.Body
	return
}

// type ModelDTO struct {
// 	ID int
// 	Body string `json:"body,omitempty"`
// 	ParentID int `json:"parent_id,omitempty"`
// 	UserID    int `json:"user_id,omitempty"`
// }

// func ToModel(dto ModelDTO) *Model {
// 	return &Model{
//     Body : dto.Body,
//     ParentID : dto.ParentID,
//     UserID : dto.UserID,
//   }
// }
