/*
 * Swagger MapSNS
 *
 * gobackend api
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package domain

import (
	"gorm.io/gorm"

	"gobackend/request"
)

// Parent - A single parent.
type Parent struct {
	Base
	Body            string  `json:"body,omitempty"`

	DeletedAt gorm.DeletedAt
}

func (parent *Parent) SetRequest(request request.Parent) {
	parent.Body = request.Body
}
