/*
 * Swagger MapSNS
 *
 * gobackend api
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
	"gobackend/controllers"
	"gobackend/core/logger"
)

var Parent = controllers.NewParent(logger.GetLogger())


// CreateParent -
func CreateParent(c *gin.Context) {
	Parent.Create(c)
}

// GetParent - Your GET endpoint
func GetParent(c *gin.Context) {
	Parent.FindByID(c)
}

// GetParents - Your GET endpoint
func GetParents(c *gin.Context) {
	Parent.FindAll(c)
}

// GetParentsByArea - Your GET endpoint

// UpdateParent -
func UpdateParent(c *gin.Context) {
	Parent.Update(c)
}
