/*
 * sample
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"go-clean-architecture/controllers"

	"github.com/gin-gonic/gin"
)

var EntityController = controllers.NewEntityController()

// CreateEntity -
func CreateEntity(c *gin.Context) {
	EntityController.Create(c)
}

// DeleteEntity -
func DeleteEntity(c *gin.Context) {
	EntityController.Delete(c)
}

// GetAllEntity - Your GET endpoint
func GetAllEntity(c *gin.Context) {
	EntityController.GetAll(c)
}

// GetByIdEntity - Your GET endpoint
func GetByIdEntity(c *gin.Context) {
	EntityController.GetById(c)
}

// UpdateEntity -
func UpdateEntity(c *gin.Context) {
	EntityController.Update(c)
}
