/*
 * sample
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Entity struct {

	Id int32 `json:"id,omitempty"`

	Text string `json:"text,omitempty"`

	CreatedAt float32 `json:"created_at,omitempty"`

	UpdatedAt float32 `json:"updated_at,omitempty"`

	DeletedAt int32 `json:"deleted_at,omitempty"`
}
