openapi: 3.0.0
info:
  title: sample
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /entities:
    get:
      operationId: get-all
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
          description: OK
        "500":
          description: Internal Server Error
      summary: Your GET endpoint
      tags: []
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: Created
        "500":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Internal Server Error
  /entities/{id}:
    delete:
      operationId: delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
    get:
      operationId: get-by-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: OK
      summary: Your GET endpoint
      tags: []
components:
  schemas:
    Entity:
      example:
        id:
          updated_at: 1.4658129805029452
          created_at: 6.027456183070403
          id: 0
          text: text
          deleted_at: 5
      properties:
        id:
          $ref: '#/components/schemas/entity'
      title: Entity
      type: object
    entity:
      example:
        updated_at: 1.4658129805029452
        created_at: 6.027456183070403
        id: 0
        text: text
        deleted_at: 5
      properties:
        id:
          type: integer
        text:
          type: string
        created_at:
          type: number
        updated_at:
          type: number
        deleted_at:
          type: integer
