/*
 * Swagger MapSNS
 *
 * gobackend api
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://http-generator.tech)
 */

package http

import (
	"github.com/gin-gonic/gin"
	"github.com/ttaki/go-clean-architecture-sample/internal/controller"
	"github.com/ttaki/go-clean-architecture-sample/pkg/logger"
)

var Attribute = controller.NewAttribute(logger.GetLogger())

// CreateAttribute -
func CreateAttribute(c *gin.Context) {
	Attribute.Create(c)
}

// DeleteAttribute -
func DeleteAttribute(c *gin.Context) {
	Attribute.Delete(c)
}

// GetAttribute -
func GetAttribute(c *gin.Context) {
	Attribute.FindByID(c)
}

// GetAttributesByEntity - Your GET endpoint
func GetAttributesByEntity(c *gin.Context) {
	Attribute.FindAllByEntity(c)
}

// UpdateAttribute -
func UpdateAttribute(c *gin.Context) {
	Attribute.Update(c)
}
